### PR TITLE
Close window on "focus lost"

### LINKED ISSUE #11: Popup stays open on focus lost
If I open the popup with `"` in normal mode and were to click on the underlying buffer, the popup stays open. The next time i press `"` again, a new one is created and this can be repeated ad infinitum.

The first time I accidentally ran into it, any keypress would throw me an invalid window id error so there wasn't even a way to get away from it.

Maybe the popup should be closed when the user clicked (unusual with vim, I know) somewhere outside the popup, or at least check that there is at most one popup open?

For illustrative purposes:

registers

### PR DESCRIPTION
**Pull request by rudotriton**
You may want to try this out, but it seems to work

closes #11

### CODE REVIEW

**Comment by tversteeg** [comment]
Thanks for the PR! I've already merged #15, which seemed a bit less magic.

**Comment by rudotriton** [comment]
That's fine. I didn't want to create an augroup to not leave the group lingering around after the window is closed.

**Comment by rudotriton** [comment]
You probably want to add a line that closes the auto group off, currently any new autocmd is added to that group, and remove the group when the window has been closed.

**Comment by tversteeg** [comment]
Those are good arguments, would you consider reopening the PR with your solution? It does sound better.

**Comment by tversteeg** [comment]
@Kyran-C fixed this in #16

**Pull request closed without merging**
