### PR TITLE
2.0: rewrite whole repository

### PR DESCRIPTION
**Pull request by tversteeg**
I've rewritten the whole repository to 100% use Lua, use modern Neovim functions, and use a Lua `.setup({})` function which is consistent with the rest of the Neovim plugins. I've also added a bunch of new configuration options.

When old `g:registers_..` variables are detected, a warning message will be shown with an automatically generated example of the new configuration.

You can try it out with the following config for Packer:

```lua
use {
	"tversteeg/registers.nvim",
	branch = "refactor",
	config = function()
		require("registers").setup()
	end,
}
```

## Breaking Changes

- All configuration is now done with a Lua table passed to the `.setup({..})` function.
- Minimum required Neovim version is 0.7.0.

## Additions

- Neovim help file, which can be accessed with `:h registers`.
- Sign highlights are now configurable.
- Opening of the window in different modes (`visual`, `normal`, etc.) can now be manually mapped, there is an example for this in the help file.
- Highlighting of cursorline can be disabled.
- Window transparency is configurable.
- All actions of the key bindings can be configured by binding a function to them, all functions can be found with `:h registers`.
- The sign bar now also optionally shows how the register will be applied, in a charwise, linewise or blockwise way.
- `registers.move_cursor_to_register` function.
- Delays can be added to every bindable key function, which can be used to replace `register_key_sleep = 1`:
```lua
local registers = require("registers")
registers.setup({
  bind_keys = {
    -- Wait a second before applying the register when selecting it with a key, this also highlights the register selected
    registers = registers.apply_register({ delay = 1 }),
    -- Also wait a second before closing the window when pressing escape
    escape = registers.close_window({ delay = 1 }),
  }
})
```

## Removals

- `min_height` and `max_height` are no longer configurable.

## Other Changes

- A specific sign bar is used instead of a manual `*reg*:` string.
- The highlight for the popup window is now `"NormalFloat"` instead of `"Normal"`, which is more consistent with other floating popup windows, since it's the default.
- The bug where the window is tiny when it's opened at the bottom of the screen is now fixed.
- Configuration of which keys to bind is more granular.
- `paste_in_normal_mode` has been replaced with allowing each mode to be configured, for example to replace the old `paste_in_normal_mode = 1`:

```lua
local registers = require("registers")
registers.setup({
  bind_keys = {
    normal = registers.show_window({ mode = "paste" }),
  }
})
```

To replace `paste_in_normal_mode = 2`:

```lua
local registers = require("registers")
registers.setup({
  bind_keys = {
    return_key = registers.apply_register({ mode = "paste" }),
  }
})
```

## TODO (for me)

- [x] `paste_in_normal_mode`.
- [x] Add registers to empty line.
- [x] Fix system clipboard (see comments below).
- [x] Fix `iabbrev`: `:iabbrev test <C-R>=2*3<CR>`.
- [x] Make paste_in_normal_mode an enum that also allows you to only paste on enter.
- [x] Allow mappings to directly reference functions in the configuration, requires that more functions are exposed.
- [x] Fix selection in visual mode.
- [x] Add option to show the type of the clipboard selection (block, line, etc.) in the sign bar with an icon.
- [x] Fix highlights when opening window from a visual selection.
- [x] `hide_only_whitespace`.
- [x] Workaround <C-R> in Telescope error.
- [x] Add migration warning when `registers.setup({})` isn't used (which will be removed after the current version).
- [x] `register_key_sleep`.
- [x] Fix prefixing the command with a number (10").

## Feedback Wanted

Any feedback and information about current usage being broken would be very appreciated. 

@QiBaobin @frandsoh @Frederick888 @HansPinckaers @Kyran-C @YuCao16 @gravndal @hexium310 @jose-elias-alvarez @weihanglo

### CODE REVIEW

**Comment by Frederick888** [comment]
Thank you for investing the time and effort!

I'm trying this out on Neovim v0.7.2, but it seems [vim.api.nvim_win_set_hl_ns()](https://github.com/neovim/neovim/commit/d879331b0dee66cb106b5bea9efc2f920caf9abd) is only available in nightly?

**Comment by tversteeg** [comment]
> Thank you for investing the time and effort!
> 
> I'm trying this out on Neovim v0.7.2, but it seems [vim.api.nvim_win_set_hl_ns()](https://github.com/neovim/neovim/commit/d879331b0dee66cb106b5bea9efc2f920caf9abd) is only available in nightly?

Thanks for checking it out, I didn't realize this feature was so recent. I'll try to find a workaround for it.

**Comment by jose-elias-alvarez** [comment]
Seems to be working well for my very simple use cases! I'll daily drive it for the next couple of days and let you know if anything comes up.

**Comment by YuCao16** [comment]
Dear @tversteeg,
There seems to be a problem in my previous PR that would cause `send to clipboard` to work only for MacOS. 
In this line: https://github.com/tversteeg/registers.nvim/blob/46dc67bba785c7ca86625b6e11fa18d14a2cd1a9/lua/registers.lua#L556
it should be `vim.cmd('let @+=@'..register)`, I have wrote a explanation file [here](https://github.com/YuCao16/MyNotes/blob/main/Notes/Other/Vim/register_explain.md).

**Comment by tversteeg** [comment]
@yucao16 I did add this again, did you set the system_clipboard option in the setup?

**Comment by YuCao16** [comment]
> @yucao16 I did add this again, did you set the `require("registers").setup({system_clipboard = true})` option in the setup?

I mean it needs to be changed from `vim.cmd('let @*=@'..register)` to `vim.cmd('let @+=@'..register)` to make it work on linux.

**Comment by tversteeg** [comment]
> I mean it needs to be changed from `vim.cmd('let @*=@'..register)` to `vim.cmd('let @+=@'..register)` to make it work on linux.

Ah sorry, misunderstood that, I'll fix it.

**Comment by YuCao16** [comment]
> > I mean it needs to be changed from `vim.cmd('let @*=@'..register)` to `vim.cmd('let @+=@'..register)` to make it work on linux.
> 
> Ah sorry, misunderstood that, I'll fix it.

Thanks, the new layout is awesome, thanks for your effort!

**Comment by tversteeg** [comment]
> I'm trying this out on Neovim v0.7.2, but it seems [vim.api.nvim_win_set_hl_ns()](https://github.com/neovim/neovim/commit/d879331b0dee66cb106b5bea9efc2f920caf9abd) is only available in nightly?

Should be fixed now!

**Comment by Frederick888** [comment]
Thank you and I can confirm it works on Neovim 0.7.2.

One small issue I noticed tho, if I `V"`, lines in the pop-up are also highlighted.

Minimal vimrc:

```vim
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath

call plug#begin('~/.vim/plugged')
Plug 'tversteeg/registers.nvim', { 'branch': 'refactor' }
call plug#end()

set nobackup
set nowritebackup
set cmdheight=2
set updatetime=300

lua << EOF
require("registers").setup({
  show_empty_registers = 0,
  hide_only_whitespace = 1,
  window_min_height    = 20,
})
EOF
```

image

**Comment by tversteeg** [comment]
@Frederick888 Thanks, I've added it to the list. I also see a mistake in your config, `window_min_height` should be `window = { min_height = .. }`

**Comment by weihanglo** [comment]
Works for me out of the box with Neovim 0.7.2. Thank you so much!

Just my little wish. Is there any plan to get this in cmdline? It would be helpful for `/` searching somehow.

**Comment by tversteeg** [comment]
@weihanglo I'll see if that's easy to implement with the current setup, otherwise I'll add it in a future version.

**Comment by tversteeg** [comment]
@Frederick888 Highlighting of visual mode should be fixed now.

**Comment by Frederick888** [comment]
It seems this branch conflicts against https://github.com/LunarWatcher/auto-pairs

In insert mode, Ctrl-R, then `"`, the quote goes into the pop-up somehow.

```vim
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath

call plug#begin('~/.vim/plugged')
Plug 'LunarWatcher/auto-pairs'
Plug 'tversteeg/registers.nvim', { 'branch': 'refactor' }
call plug#end()

set nobackup
set nowritebackup
set cmdheight=2
set updatetime=300

let g:AutoPairsCenterLine = 0
let g:AutoPairsMapCR = 0
let g:AutoPairsMapBS = 1
let g:AutoPairsMoveExpression = '<M-%key>'
let g:AutoPairsShortcutIgnore = ''
let g:AutoPairsShortcutToggleMultilineClose = ''

lua << EOF
require("registers").setup({
  show_empty = 0,
  hide_only_whitespace = 1,
})
EOF
```

**Comment by tversteeg** [comment]
@Frederick888 this is a difficult one, the only solution I can find for fixing this is putting the registers window in normal mode when opening it and switching back to insert mode after closing it, but this will ruin the `.` command..

**Comment by Frederick888** [comment]
I worked with auto-pairs' maintainer and now registers.nvim rewrite can work with auto-pairs by configuring `let g:AutoPairsFiletypeBlacklist = ['registers']` (https://github.com/LunarWatcher/auto-pairs/pull/68).

**Pull request merged**
